//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace task_distribution_app.Models.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class TDIFFICULTYLEVEL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TDIFFICULTYLEVEL()
        {
            this.TTASK = new HashSet<TTASK>();
        }
    
        public int DIFFICULTYLEVEL_ID { get; set; }
        public Nullable<int> DIFFICULTYLEVEL_SCORE { get; set; }
        public string DIFFICULTYLEVEL_NAME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TTASK> TTASK { get; set; }
    }
}
