//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace task_distribution_app.Models.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class TUSER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TUSER()
        {
            this.TTASK = new HashSet<TTASK>();
            this.TTASK1 = new HashSet<TTASK>();
        }
    
        public int USER_ID { get; set; }
        public string USER_USERNAME { get; set; }
        public string USER_FULLNAME { get; set; }
        public string USER_PASSWORD { get; set; }
        public Nullable<int> USER_ROL_ID { get; set; }
    
        public virtual TROLE TROLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TTASK> TTASK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TTASK> TTASK1 { get; set; }
    }
}
